# claims/pdf_map.py

"""
This file is the definitive map between our application's data
and the cryptic field names in the J101E PDF form.
It was generated by manually filling the PDF with unique identifiers
and then extracting the data.
"""

# 1. Mapping for single, straightforward fields
PDF_FIELD_MAP = {
    # Page 1 - Applicant
    'applicant_ref_no': '1 a',
    'applicant_name': '1 a2',
    'applicant_age': '1 c',
    'applicant_address_1': '1 e1',
    'applicant_address_2': '1 e2',
    'applicant_address_3': '1 e3',
    'applicant_phone_code': '1 e6',     
    'applicant_phone_number': '1 e7',      
    'applicant_work_address_1': '1 f1',
    'applicant_work_address_2': '1 f2',
    'applicant_work_phone': '1 f7',
    'applicant_police_station': '1 g', 

    # Page 1 - Respondent (Defendant)
    'respondent_name': '1 h',
    'respondent_age': '1 j',
    'respondent_address_1': '1 l1',
    'respondent_address_2': '1 l2',
    'respondent_phone_code': '1 l6',    
    'respondent_phone_number': '1 l7',     
    'respondent_work_address_1': '1 m1',
    'respondent_work_phone': '1 m7',

    # Page 2 - Reasons, History & Claim
    'reason_liable_1': '2A1',
    'reason_liable_2': '2A2',
    'reason_care_1': '2B1',
    'reason_care_2': '2B2',
    'date_not_supported': '2 C1',
    'claim_total': '2 D1', 
    'first_payment_date': '2 J1',
    'payment_day': '2 J2',
    'payment_made_to': '2 J3',
    'payment_in_favour_of': '2 J4',
    'other_contributions_1': '2 K1',
    'other_contributions_2': '2 K2',

    # Page 3 - Applicant's Assets
    'asset_fixed_property': '3 A1',
    'asset_investments': '3 A2',
    'asset_savings': '3 A3',
    'asset_shares': '3 A4',
    'asset_motor_vehicles': '3 A5',

    # Page 3 - Applicant's Income & Deductions
    'income_gross_salary': 'gross',
    'income_other_1': 'incomeA',
    'income_total': 'totalIncome',
    'deduction_tax': 'tax',
    'deduction_medical_aid': 'maid',
    'deduction_pension': 'pen',
    'deduction_other': 'otherA',
    'income_nett_salary': 'nett',  

    # Page 3 & 4 - Expenditure Table (Self, Child, Total Columns)
    'expense_self_lodging': '3 C 1',    'expense_child_lodging': '3 D 1',    'expense_total_lodging': '3 E 1',
    'expense_self_groceries': '3 C 2',  'expense_child_groceries': '3 D 2',  'expense_total_groceries': '3 E 2',
    'expense_self_utilities': '3 C 3',  'expense_child_utilities': '3 D 3',  'expense_total_utilities': '3 E 3',
    'expense_self_rates_taxes': '3 C 4','expense_child_rates_taxes': '3 D 4','expense_total_rates_taxes': '3 E 4',
    'expense_self_laundry': '3 C 5',    'expense_child_laundry': '3 D 5',    'expense_total_laundry': '3 E 5',
    'expense_self_telephone': '3 C 7',  'expense_child_telephone': '3 D 7',  'expense_total_telephone': '3 E 7',
    
    'expense_self_clothing': '3 C 13',  'expense_child_clothing': '3 D 13',  'expense_total_clothing': '3 E 13',
    'expense_child_school_uniforms': '3 D 14', 'expense_total_school_uniforms': '3 E 14', # No 'self' field
    
    'expense_self_transport_public': '3 C 15', 'expense_child_transport_public': '3 D 15', 'expense_total_transport_public': '3 E 15',
    'expense_self_car_insurance': '3 C 16',    'expense_child_car_insurance': '3 D 16',    'expense_total_car_insurance': '3 E 16',
    'expense_self_car_maintenance': '3 C 17',  'expense_child_car_maintenance': '3 D 17',  'expense_total_car_maintenance': '3 E 17',
    'expense_self_fuel': '3 C 18',             'expense_child_fuel': '3 D 18',             'expense_total_fuel': '3 E 18',
    
    'expense_child_school_fees': '3 D 19',  'expense_total_school_fees': '3 E 19',
    'expense_child_stationery': '3 D 20',   'expense_total_stationery': '3 E 20',
    'expense_child_extramural': '3 D 21',   'expense_total_extramural': '3 E 21',

    'expense_self_medical': '3 C 22',   'expense_child_medical': '3 D 22',   'expense_total_medical': '3 E 22',
    'expense_self_medication': '3 C 23', 'expense_child_medication': '3 D 23', 'expense_total_medication': '3 E 23',

    'expense_self_entertainment': '3 C 26', 'expense_child_entertainment': '3 D 26', 'expense_total_entertainment': '3 E 26',
    'expense_self_other': '3 C 55',         'expense_child_other': '3 D 55',         'expense_total_other': '3 F 55', # Note the F key

    # Page 5 - Grand Totals (using new keys from your mapping)
    'expenditure_total_self_col': '3 D 60',
    'expenditure_total_child_col': '3 E 60',
    'expenditure_total_final': '3 F 60',
}

# 2. Mapping for fields that are filled character-by-character
PDF_CHAR_MAP = {
    'applicant_dob': ['1 b1', '1 b2', '1 b3', '1 b4', '1 b5', '1 b6'], # d,d,m,m,y,y
    'applicant_id': ['1 d1', '1 d2', '1 d3', '1 d4', '1 d5', '1 d6', '1 d7', '1 d8', '1 d9', '1 d10', '1 d11', '1 d12', '1 d13'],
    'respondent_dob': ['1 i1', '1 i2', '1 i3', '1 i4', '1 i5', '1 i6'], # d,d,m,m,y,y
    'respondent_id': ['1 k1', '1 k2', '1 k3', '1 k4', '1 k5', '1 k6', '1 k7', '1 k8', '1 k9', '1 k10', '1 k11', '1 k12', '1 k13'],
}

# 3. Structured mapping for the children table
PDF_CHILD_MAP = {
    0: {'amount': '2 D2', 'name': '2 D3', 'dob': ['2 D 4a', '2 D 4b', '2 D 4c', '2 D 4d', '2 D 4e', '2 D 4f', '2 D 4g', '2 D 4h']},
    1: {'amount': '2 E2', 'name': '2 E3', 'dob': ['2 E 4a', '2 E 4b', '2 E 4c', '2 E 4d', '2 E 4e', '2 E 4f', '2 E 4g', '2 E 4h']},
    2: {'amount': '2 F2', 'name': '2 F3', 'dob': ['2 F 4a', '2 F 4b', '2 F 4c', '2 F 4d', '2 F 4e', '2 F 4f', '2 F 4g', '2 F 4h']},
    3: {'amount': '2 G2', 'name': '2 G3', 'dob': ['2 G 4a', '2 G 4b', '2 G 4c', '2 G 4d', '2 G 4e', '2 G 4f', '2 G 4g', '2 G 4h']},
    4: {'amount': '2 H2', 'name': '2 H3', 'dob': ['2 H 4a', '2 H 4b', '2 H 4c', '2 H 4d', '2 H 4e', '2 H 4f', '2 H 4g', '2 H 4h']},
    5: {'amount': '2 I2', 'name': '2 I3', 'dob': ['2 I 4a', '2 I 4b', '2 I 4c', '2 I 4d', '2 I 4e', '2 I 4f', '2 I 4g', '2 I 4h']},
}